version: '3.8'

services:
  web:
    build:
      context: ./docker
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - webnet

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: webapp
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - webnet

volumes:
  mysql-data:

networks:
  webnet:
