version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: evoting_vulnerable_app
    ports:
      - "8181:8181"
    volumes:
      - ./application/evoting:/var/www/html/evoting
      - ./logs:/var/log/apache2
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root_password
      DB_NAME: evoting
      APP_DEBUG: "true"
      APP_ENV: "development"
      SECRET_KEY: "this_is_a_secret_key_12345"
      ADMIN_BACKDOOR: "Admin187:password187"
    networks:
      - evoting_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8181/evoting/login1.php"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: mysql:5.7
    container_name: evoting_mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: evoting
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: evoting_user
      MYSQL_PASSWORD: evoting123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/EvotingA.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./db/Triggers_and_Views_B.sql:/docker-entrypoint-initdb.d/02-triggers.sql
    networks:
      - evoting_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: evoting_phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password
    depends_on:
      - db
    networks:
      - evoting_network

networks:
  evoting_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
