version: '3.8'

services:
  web:
    build: .
    ports:
      - "8181:8181"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: evoting_user
      DB_PASSWORD: evoting_password
      DB_NAME: evoting_db

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: evoting_db
      MYSQL_USER: evoting_user
      MYSQL_PASSWORD: evoting_password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
